# Generated by Django 3.2.23 on 2024-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='serial_number',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
