# Generated by Django 4.2.9 on 2024-01-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='serial_number',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
